#!/usr/bin/env bash

chmod 400 ./source/id_rsa
cp ./source/config ~/.ssh/config
git clone git@github.com:jpolitz/pyret-grading-example.git

rm ./source/id_rsa

pushd /autograder/code.pyret.org
npm start &
popd

bash pyret-grading-example/grade
